### ISSUE TITLE
Task 1: Folder re-structuring and make file updating

### ISSUE THREAD

**Issue by abhinavachanta** [abhinavachanta/AlternateBitProtocolSimulator#1]
Code committed after folder re-structuring and updating make file.
Review pending.

**Comment by syedomarazam** [comment]
vendor folder should go under lib folder. I currently see it under include folder.

**Comment by syedomarazam** [comment]
Have you completed makefile? If you are still working on it. Ill give you a tip. 

1)Try to generate all .exe files (ABP, SUBNET, SENDER and RECEIVER) in one “all” statement. 

2)delete all .exe and .o files in one “clean” statement. Its will reduce your LOC.

**Comment by abhinavachanta** [comment]
> vendor folder should go under lib folder. I currently see it under include folder.

Hi Syed, 
The vendor folder is under 'include' folder because it contains the header(.hpp) files and as per my understanding, the header files should go inside include folder hierarchy. 
Note: I could have put all header files directly in include, but I added sub-folders inside include for better structuring and code understanding.

**Comment by abhinavachanta** [comment]
> Have you completed makefile? If you are still working on it. Ill give you a tip.
> 
> 1)Try to generate all .exe files (ABP, SUBNET, SENDER and RECEIVER) in one “all” statement.
> 
> 2)delete all .exe and .o files in one “clean” statement. Its will reduce your LOC.

Good idea in general, but as per good coding practices I would say it is better to keep them separate. A user might want to run only the simulator and not the test cases. In that case, putting everything in one 'all' statement would force the user to run everything (simulator as well as test cases) which would result in higher computation time. Hence I think it may be better to separate the test cases and main implementation. Suggestions?

**Comment by syedomarazam** [comment]
I know vendor folder have .hpp files. But its from 3rd party and professor confirmed in last lecture to put it under lib folder.

**Comment by abhinavachanta** [comment]
> I know vendor folder have .hpp files. But its from 3rd party and professor confirmed in last lecture to put it under lib folder.

Hi Syed,
I was unaware of that, thank you so much for letting me know. I'll do the suggested changes and resubmit the file :)

**Comment by syedomarazam** [comment]
for makefile:
1) in clean statements: you can remove this line "-for d in src/data_structures; do (cd $$d; rm -f *.o *~ ); done" becasue we aren't generating .o files in data_structures folder anymore. 

2) In line 23 and 44 : you can rename "../data_structures/message.o" as it created confusion in the reader's mind. a user might think he has to navigate one directory back and go to data structures folder. this path actually doesn't exist.

3) you could probably rearrange code to give more readability to users. something like this
       --> creating bin and build folders
       --> all:
       --> simulator:
       --> tests:
       --> main.o:
       --> test_sender_main.o:
       --> test_receiver_main.o:
       --> test_subnet_main.o:
       --> clean_simulator:
       --> clean_tests:

**Comment by syedomarazam** [comment]
you can update README file as things have changed now. you can refer to my project README file if you want.

**Comment by syedomarazam** [comment]
you can probably rename main.cpp files for the sender, receiver, subnet. I know it is in separate folders but if someone by mistake swap those files, they won't know unless they open and see the contents. In this way, you can get rid of separate folders and keep all .cpp files in test/src folder itself rather than 3 sub-folders inside test/src.

Even this may (same name for all main.cpp files) introduces errors in the makefile. (professor discussed this thing in class and asked to rename main files)

**Comment by syedomarazam** [comment]
makefile: clean

**Comment by pcsmartapps** [comment]
1- Under test folder, names of the main functions for sender, receiver and subnet are the same
it may be little confusing if you are debugging
2- the  .o files for sender, receiver and subnet are same "main.o", it may be little confusing if you are debugging
3- you split build directory to src and test, and also bin should have the same structure
4- when you do make clean_tests it cleans all .exe files including top_model ABP.exe, it should only clean the test .exe files
